// <auto-generated />
using System;
using EasyControl.Repositorio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EasyControl.Repositorio.Migrations
{
    [DbContext(typeof(ConfiguracaoContexto))]
    [Migration("20180613220417_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EasyControl.Dominio.Convenio._1.Entidade.Convenio", b =>
                {
                    b.Property<int>("IdConvenio")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasMaxLength(50);

                    b.HasKey("IdConvenio");

                    b.ToTable("Convenios");
                });

            modelBuilder.Entity("EasyControl.Dominio.Pessoa.Funcionario._1.Entidade.Permissao", b =>
                {
                    b.Property<int>("IdPermissao")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdFuncionario");

                    b.Property<string>("Key")
                        .HasMaxLength(50);

                    b.HasKey("IdPermissao");

                    b.ToTable("Permissao");
                });

            modelBuilder.Entity("EasyControl.Dominio.Pessoa.Funcionario.Colaborador._1.Entidade.Colaborador", b =>
                {
                    b.Property<int>("IdColaborador")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf");

                    b.Property<string>("Nome")
                        .HasMaxLength(50);

                    b.Property<string>("Rg");

                    b.Property<string>("Sobrenome");

                    b.HasKey("IdColaborador");

                    b.ToTable("Colaborador");
                });

            modelBuilder.Entity("EasyControl.Dominio.Pessoa.Funcionario.Colaborador._1.Entidade.ColaboradorPermissao", b =>
                {
                    b.Property<int>("IdColaborador");

                    b.Property<int>("IdPermissao");

                    b.HasKey("IdColaborador", "IdPermissao");

                    b.HasIndex("IdPermissao");

                    b.ToTable("ColaboradorPermissao");
                });

            modelBuilder.Entity("EasyControl.Dominio.Pessoa.Funcionario.Medico._1.Entidade.ConvenioCredenciado", b =>
                {
                    b.Property<int>("IdMedico");

                    b.Property<int>("IdConveio");

                    b.Property<int?>("ConvenioIdConvenio");

                    b.HasKey("IdMedico", "IdConveio");

                    b.HasIndex("ConvenioIdConvenio");

                    b.ToTable("ConvenioCredenciado");
                });

            modelBuilder.Entity("EasyControl.Dominio.Pessoa.Funcionario.Medico._1.Entidade.Especialidade", b =>
                {
                    b.Property<int>("IdEspecialidade")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdMedico");

                    b.Property<string>("Nome")
                        .HasMaxLength(50);

                    b.HasKey("IdEspecialidade");

                    b.HasIndex("IdMedico");

                    b.ToTable("Especialidade");
                });

            modelBuilder.Entity("EasyControl.Dominio.Pessoa.Funcionario.Medico._1.Entidade.Medico", b =>
                {
                    b.Property<int>("IdMedico")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf");

                    b.Property<string>("Nome")
                        .HasMaxLength(50);

                    b.Property<string>("Rg");

                    b.Property<string>("Sobrenome");

                    b.HasKey("IdMedico");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("EasyControl.Dominio.Pessoa.Funcionario.Medico._1.Entidade.Procedimento", b =>
                {
                    b.Property<int>("IdEspecialidade")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EspecialidadeIdEspecialidade");

                    b.Property<int>("IdProcedimento");

                    b.Property<string>("Nome")
                        .HasMaxLength(50);

                    b.HasKey("IdEspecialidade");

                    b.HasIndex("EspecialidadeIdEspecialidade");

                    b.ToTable("Procedimento");
                });

            modelBuilder.Entity("EasyControl.Dominio.Pessoa.Paciente._1.Entidade.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ConvenioIdConvenio");

                    b.Property<string>("Cpf");

                    b.Property<string>("Nome")
                        .HasMaxLength(50);

                    b.Property<string>("Rg");

                    b.Property<string>("Sobrenome");

                    b.HasKey("IdPaciente");

                    b.HasIndex("ConvenioIdConvenio");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("EasyControl.Dominio.Pessoa.Funcionario.Colaborador._1.Entidade.ColaboradorPermissao", b =>
                {
                    b.HasOne("EasyControl.Dominio.Pessoa.Funcionario.Colaborador._1.Entidade.Colaborador", "Colaborador")
                        .WithMany("Permissoes")
                        .HasForeignKey("IdColaborador")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EasyControl.Dominio.Pessoa.Funcionario._1.Entidade.Permissao", "Permissao")
                        .WithMany("Colaboradores")
                        .HasForeignKey("IdPermissao")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EasyControl.Dominio.Pessoa.Funcionario.Medico._1.Entidade.ConvenioCredenciado", b =>
                {
                    b.HasOne("EasyControl.Dominio.Convenio._1.Entidade.Convenio", "Convenio")
                        .WithMany("MedicosCredenciados")
                        .HasForeignKey("ConvenioIdConvenio");

                    b.HasOne("EasyControl.Dominio.Pessoa.Funcionario.Medico._1.Entidade.Medico", "Medico")
                        .WithMany("ConveniosCredenciados")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EasyControl.Dominio.Pessoa.Funcionario.Medico._1.Entidade.Especialidade", b =>
                {
                    b.HasOne("EasyControl.Dominio.Pessoa.Funcionario.Medico._1.Entidade.Medico", "Medico")
                        .WithMany("Especialidades")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EasyControl.Dominio.Pessoa.Funcionario.Medico._1.Entidade.Procedimento", b =>
                {
                    b.HasOne("EasyControl.Dominio.Pessoa.Funcionario.Medico._1.Entidade.Especialidade", "Especialidade")
                        .WithMany("Procedimentos")
                        .HasForeignKey("EspecialidadeIdEspecialidade");
                });

            modelBuilder.Entity("EasyControl.Dominio.Pessoa.Paciente._1.Entidade.Paciente", b =>
                {
                    b.HasOne("EasyControl.Dominio.Convenio._1.Entidade.Convenio", "Convenio")
                        .WithMany("Pacientes")
                        .HasForeignKey("ConvenioIdConvenio");
                });
#pragma warning restore 612, 618
        }
    }
}
